### ISSUE TITLE
Unable to load asset: packages/flutter_google_places_autocomplete/assets/google_white.png

### ISSUE THREAD

**Issue by tegab** [lejard-h/flutter_google_places#19]
I am getting this error every time I try to debug.

Exception has occurred.
Unable to load asset: packages/flutter_google_places_autocomplete/assets/google_white.png

I have tried ^0.1.1 ^0.1.0 still does not work.

Please help...

thnx

**Comment by lejard-h** [comment]
Sorry I forgot to add that to the README.

you need to had following assets to you pubspec.yaml

```
 - packages/flutter_google_places_autocomplete/assets/google_black.png
 - packages/flutter_google_places_autocomplete/assets/google_white.png
```

**Comment by lejard-h** [comment]
it should be fix in the last version, keep me updated if not

**Comment by Phelickz** [comment]
hey, how did y'all resolve the issue? I just got the same error.
