### ISSUE TITLE
Getting the Place Details using AutoCompleteTextField

### ISSUE THREAD

**Issue by makkasbed** [lejard-h/flutter_google_places#25]
Hello,

Is there a way to get the place details using autocompletetextfield of this plugin?

Regards,

**Comment by lejard-h** [comment]
not directly with the library. 

check the example 
https://github.com/lejard-h/flutter_google_places/blob/master/example/lib/main.dart

It use `package:google_maps_webservice/places.dart` to get place details [here](https://github.com/lejard-h/flutter_google_places/blob/master/example/lib/main.dart#L92)

**Comment by savasadar** [comment]
Future<Null> displayPrediction(Prediction p, ScaffoldState scaffold) async {
  if (p != null) {
    // get detail (lat/lng)
    PlacesDetailsResponse detail = await _places.getDetailsByPlaceId(p.placeId);
    final lat = detail.result.geometry.location.lat;
    final lng = detail.result.geometry.location.lng;

    scaffold.showSnackBar(
      SnackBar(content: Text("${p.description} - $lat/$lng")),
    );
  }
}
