### ISSUE TITLE
custom scaffold footer overide not working

### ISSUE THREAD

**Issue by naumanahmed19** [lejard-h/flutter_google_places#28]
I am trying to change powerd by google logo. But its not overriding can you please check it althought it works for overlay

```
  CustomSearchScaffold()
      : super(
          apiKey: kGoogleApiKey,
          language: "en",
          components: [Component(Component.country, "pk")],
          hint: "Search a location",
          footer: Text("My Footer Text"),
        );
```

**Comment by lejard-h** [comment]
The issue here is that the footer should not be visible when using custom scaffold.

I you want an other footer or just no footer you need to manually handle it inside your scaffold.

I will publish the fix soon

**Comment by lejard-h** [comment]
the `footer` naming is actually confusing since the logo is not in the footer but part of the result list,
I renamed it to `logo` in the last version, so you just need to use it inside you CustomScaffoldState

```
Widget build(BuildContext context) {
    final appBar = AppBar(title: AppBarPlacesAutoCompleteTextField());
    final body = PlacesAutocompleteResult(
      onTap: (p) {
        displayPrediction(p, searchScaffoldKey.currentState);
      },
      logo: Row(
        children: [FlutterLogo()],
        mainAxisAlignment: MainAxisAlignment.center,
      ),
    );
    return Scaffold(key: searchScaffoldKey, appBar: appBar, body: body);
  }
```
