### ISSUE TITLE
tried to run example project in in flutter, got some gradle NDK error!!!!!   

### ISSUE THREAD

**Issue by DeepStyles** [lejard-h/flutter_google_places#31]

**Comment by lejard-h** [comment]
any informations ?

flutter version ?
plugin version ?
android version ?

**Comment by anlarosa** [comment]
I have the same issue.
So I install NDK from androidSDK but I got another error.
If the example was fully functional would be great.

The error:

> 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
> 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
> 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
> 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> FAILURE: Build failed with an exception.
> * Where:
> Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 21
> * What went wrong:
> A problem occurred evaluating script.
> > Could not find method google() for arguments [] on repository container.
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
>   Command: D:\Profiles\alarosa\Documents\isolrelmode\flutter_google_places\example\android\gradlew.bat app:properties
> Please review your Gradle project setup in the android/ folder.

$ flutter doctor -v

> [√] Flutter (Channel beta, v0.11.10, on Microsoft Windows [Versione 10.0.15063], locale it-IT)
>     • Flutter version 0.11.10 at C:\src\flutter
>     • Framework revision c27c4a265e (4 days ago), 2018-11-26 17:07:24 -0500
>     • Engine revision eebc6a5895
>     • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
> 
> [√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
>     • Android SDK at d:\Profiles\alarosa\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.1)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 26.0.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
> 
> [!] IntelliJ IDEA Community Edition (version 2018.1)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.io/intellij-setup/#installing-the-plugins
> 
> [√] VS Code (version 1.29.1)
>     • VS Code at d:\Profiles\alarosa\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 2.21.0
> 
> [√] VS Code, 64-bit edition (version 1.29.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 2.21.0
> 
> [√] Connected device (1 available)
>     • HUAWEI VNS L31 • 4TE0216A14001341 • android-arm64 • Android 7.0 (API 24)
> 
> ! Doctor found issues in 1 category.

**Comment by GianfrancoMS** [comment]
I have the same issue. Can't run the example because of NDK error.

**Comment by shakes80** [comment]
+1 Same issue here.

**Comment by shakes80** [comment]
This is an old gradle2.3.3 issue.  
See the following: 
1. https://stackoverflow.com/questions/44730178/getting-warning-ndk-is-missing-a-platforms-directory-with-no-ndk?rq=1
2. https://stackoverflow.com/questions/42682357/how-to-fix-android-studios-2-3-ndk-bug
3. https://github.com/requery/requery/issues/467

Fix by:
- updating gradle-wrapper.properties in the example
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`
- update the dependency in build.gradle
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
    }
```

PR submitted. 
If it's the correct fix, please let me know.
