### ISSUE TITLE
How to get only name city

### ISSUE THREAD

**Issue by anhtu0101** [lejard-h/flutter_google_places#32]
Hello,
Thank you very much for your flutter plugin.
I have a question, is it possible to get only name city of Place

I used the code to get name Place
new Text("${p.description} - $lat/$lng"))

- Ex: Heathrow Airport (LHR), Longford, UK
- I want: Longford

Thanks in advance

**Comment by lejard-h** [comment]
you can use the `(cities)` type 

https://developers.google.com/places/web-service/autocomplete#place_types

```
PlacesAutocomplete.show(
   types: '(cities)',
);
```
