### ISSUE TITLE
Incompatible constructor with GoogleMapsPlaces

### ISSUE THREAD

**Issue by korbacsk** [lejard-h/flutter_google_places#33]
Need Fix:
Fix lib/src/flutter_google_places.dart. (-25 points)

Analysis of lib/src/flutter_google_places.dart failed with 1 error:

line 324 col 31: Too many positional arguments: 0 expected, but 1 found.

apiKey parameter now optional.

**Comment by stt106** [comment]
@lejard-h please can we get this fixed?

**Comment by lejard-h** [comment]
sorry should be fix now
