### ISSUE TITLE
PlacesAutocomplete does not displays list.

### ISSUE THREAD

**Issue by replysam2009** [lejard-h/flutter_google_places#35]
I followed the steps mentioned in the readme file but the autocomplete widget is not returning any results. 
FYI: Created a new API key in google console (Places SDK Android)

**Comment by lejard-h** [comment]
Not sure `Places SDK Android` will work since it use google web service.

Did you try with Places API for web ?

**Comment by lejard-h** [comment]
duplicate of https://github.com/lejard-h/flutter_google_places/issues/18
